GET http://localhost:3000/news?search=ruby


###

GET http://localhost:3000/users

###

GET http://localhost:3000/users/2

###

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Ben",
  "subscriber": "yes"
}

###

PATCH http://localhost:3000/users/3
Content-Type: application/json

{
  "name": "Benny"
}

###
DELETE http://localhost:3000/users/3